name: Build PDF Book
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Generate SUMMARY.md
        run: python scripts/generate_summary.py
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      
      - name: Install mdbook PDF Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          cargo install mdbook-pdf
      
      - name: Build PDF
        run: mdbook-pdf
      
      - name: Organize PDF by Date
        run: |
          python scripts/organize_pdf.py book.pdf
          mkdir -p published_pdfs
          cp -r published_pdfs ./published_pdfs || true
      
      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-pdf
          path: book.pdf
          
      - name: Upload Organized PDFs
        uses: actions/upload-artifact@v3
        with:
          name: published-pdfs
          path: published_pdfs
          
      # Using softprops/action-gh-release instead of deprecated create-release and upload-release-asset
      - name: Create Release and Upload PDF
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Book Release v${{ github.run_number }}
          files: |
            ./book.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}